# YouTube API Key
API_KEY = "XXXXXXXXXXXX"
#API_KEY = "XXXXXXXXXXX"

# Database Configuration
DB_USERNAME = "XXXXXXXXXXXX"
DB_PASSWORD = "XXXXXXXXXXXX"
DB_NAME = "XXXXXXXXXXXX"
COLLECTION_NAME = "XXXXXXXXXXXX"
